### ISSUE TITLE
Clean up the base network

### ISSUE THREAD

**Issue by the-maldridge** [void-linux/void-infrastructure#110]
Right now networking in Void is a bit of a mess.  We have some machines that are dualstacked some that are ipv4 only, some that are behind a NAT, and all of them are sitting on our private global VPN.  This is all managed by ansible playbooks which conduct crimes against jinja2 and lead to spectacular failures like in #96.  Its time to re-evaluate how we bring the network up, and whether dhcpcd is still the best option here.

Ideally I want to evaluate something that satisfies (1) human interaction so that if we're on a box fixing something by hand its not that hard to do and (2) better automation support, i.e. no more jinja2 abuses.  This is probably a good opportunity to evaluate other technologies like netplan or networkmanager for bringing up the network and managing the routes.

The ansible network role also provides the iptables handler which I'd like to deprecate.  I want to start moving towards nftables for dualstacking the entire network, and this seems like a good point in time to start that work.  This will likely mean splitting that role and then fixing all the roles in void-ansible-roles to recognize the split.

This is a help wanted item.

**Comment by heliocat** [comment]
I've been thinking about this and the approach that I'd take is to switch the static addressed hosts from dhcpcd management to using ifupdown. It'll lose the flexibility of running everything through a daemon, but I think it will solve both the human interaction criteria and the cleaner templating requirement. It also has the benefit of guaranteeing that the network is configured before runsvdir is started since ifupdown is part of core-services and runs in 1. For the hosts that are dhcp (which I believe is only c-lej-de.m.voidlinux.org) we'll still use dhcpcd, but removing all of the static-or-dynamic stuff from the template will make it much less awful to work with.

Once that split is done, we should update the various network-dependent run scripts to do a quick network availability check and have them bail out early if it isn't available. That will avoid the races at least for the short term since they will always pass on the static hosts (modulo actually broken networking), and will force some degree of ordering onto the dynamic ones.

Medium-term using netplan might be a better choice but I think getting the world into a functional, if exceptionally un-sexy, state should be the first order of business. Similarly, moving from iptables to nftables is a good idea but should be done after the network configuration is easier to deal with and think about.

Let me know what you think and I can start writing a template for ifupdown. I did write a kind of brute-force readiness notification hook for dhcpcd last night, so if we decide to stick with dhcpcd across the board we can use it but it isn't pretty.

**Comment by bobertlo** [comment]
I've been working on the darkside lately and found managing network manager with ansible is actually pretty painless. I am starting to rewrite some similar roles soon with an open source license.

I have only rudimentary (and poor) experience with netplan but I think for 1) it's a no... and 2) it's probably worse off than network manager.

I really liked my experience with awall and general network configuration in alpine. I wonder how portable that stuff is? But that is a whole different thing.

**Comment by the-maldridge** [comment]
`awall` is completely portable, and I have a package for it on my personal branch, but I don't know its wise to import it as its iptables based which means it does a huge amount of rule generation, something I typically try to avoid.

**Comment by the-maldridge** [comment]
The base network has been cleaned up to the level that I want to achieve.
