### ISSUE TITLE
arm repos still in stage due to obsolete pkgs

### ISSUE THREAD

**Issue by xtraeme** [void-linux/void-infrastructure#52]
The arm repositories are still in staged state due to obsolete packages still being available in repository index.

- sigil -> linked against python-3.6, nocross due to missing qt5-webengine
- python3-iwlib -> linked against python-3.6

Please perform a repo cleanup to fix them.

**Comment by the-maldridge** [comment]
I assume the non-arm repos.  A clean is running there now.

**Comment by Johnnynator** [comment]
32bit arm musl and aarch64* are still staged. 32bit arm seem to be fine now.

**Comment by the-maldridge** [comment]
Ok. I'll run a manual clean against those when I get back home.

**Comment by xtraeme** [comment]
The aarch64 builders still have the staged issue:

```
=> Creating libcap-2.29_2.aarch64.xbps for repository /host/binpkgs ...
=> Creating libcap-dbg-2.29_2.aarch64.xbps for repository /host/binpkgs/debug ...
=> libcap-2.29_2: running post-pkg hook: 00-register-pkg ...
=> Registering new packages to /host/binpkgs
Inconsistent shlibs:
  libpython3.6m.so.1.0 (provided by: python3; used by: python3-iwlib, python3-pyenet)
```

**Comment by Duncaen** [comment]
Cleaned the aarch64 indexes, they should be unstaged after the next build.

**Comment by xtraeme** [comment]
did you do this manually? if so, what exactly?

**Comment by xtraeme** [comment]
I've got my `base-chroot-v2` branch ready, gonna commit and submit PR.

With this branch we will make sure that **everyones** using xbps-src with the same commit will get the same result if using **official repositories**.

Will make it public soon :-)

**Comment by Duncaen** [comment]
Yes this needs to be done manually and takes some time, otherwise xbps-rindex might delete wrong noarch packages.
First I take the workers down that share hostdirs (and noarch packages therefor), then run a script that first does `xbps-rindex -a` on all noarch packages, then `xbps-rindex -c`, followed by `xbps-rindex -r`.

**Comment by Duncaen** [comment]
So the `xbps-rindex -R` flag which would allow removing single packages from the index would actually help a lot and make it faster in those cases, where we don't really want to clean the full index.
Other than that, noarch packages in shared hostdirs suck, there is no way to have two different architecture index have different versions, because each architectures `xbps-rindex -r` would delete the others version.

**Comment by the-maldridge** [comment]
Thanks for following up on this one. Aarch64 was still chewing on packages
when I went to bed.

**Comment by xtraeme** [comment]
Looks good now, cheers :+1:
